import { motion } from "framer-motion";
import { Card } from "../components/Card";
import { Button } from "../components/Button";
import { MotionPage } from "../motion/MotionPage";
import { fade } from "../motion/animations";

export default function Plans() {
  return (
    <MotionPage>
      <div className="grid">
        <motion.div {...fade(0)}>
          <h1 className="h1">Plans</h1>
          <p className="p">Workout + meal plans, regenerated by AI.</p>
        </motion.div>

        <motion.div {...fade(0.08)}>
          <Card>
            <h2 className="h2">Workout Plan</h2>
            <p className="p">Upper/Lower split (Gym). Progressive overload, 4-week block.</p>
            <div style={{ marginTop: 14 }}>
              <Button label="Regenerate with AI" onClick={() => {}} />
            </div>
          </Card>
        </motion.div>

        <motion.div {...fade(0.14)}>
          <Card>
            <h2 className="h2">Meal Plan</h2>
            <p className="p">High-protein, moderate carbs. Tuned to your activity level.</p>
            <div style={{ marginTop: 14 }}>
              <Button label="Regenerate with AI" onClick={() => {}} />
            </div>
          </Card>
        </motion.div>
      </div>
    </MotionPage>
  );
}